#!/bin/bash
#NOTE PYTHON IS EXCLUDED FROM THE COMPILATION SYSTEM BECAUSE IT IS AN INTERPRETIVE LANGUAGE

#Checks if Makefiles are already made, if so, it deletes them so that the updated ones are created.
CLEAR_MAKEFILES=`find -name Makefile | grep "\./Makefile"`
if [[ ${CLEAR_MAKEFILES} == "./Makefile" ]]
then
    make distclean &> temp
    rm -rf temp
fi


#Add new languages and compiler commands here to check for new ones.
echo "Checking for existing compilers..."
COMPILER_CHECK=( make javac g++ gcc f77 cobc )
LANG_CHECK=( Make Java C++ C Fortran Cobol )
EXT_LANGS=( .java .cpp .c .f .cob )

#Sort extension languages Function
function mysortLangExt { 
    for i in ${EXT_LANGS[@]}; 
    do 
	echo "$i";
    done | sort -n 
}




LANGS_EXTENSIONS=( $(mysortLangExt) )





for (( i=0; i<"${#COMPILER_CHECK[@]}"; i++ ));
do
    COMPILE=$(which "${COMPILER_CHECK[${i}]}")
    echo -n  "${LANG_CHECK[${i}]}..."
    if [[ ${COMPILE} == */usr/bin/* ]]
    then
	echo "Yes"
    else
	echo "No"
    fi
done

echo ""
echo ""

GEN_FILENAME=Makefile
IFS='/' CURR_DIR=($PWD)
CURRENT="${CURR_DIR[${#CURR_DIR[@]}-1]}"
PROG=("${CURRENT}")

len=`expr ${#CURR_DIR[@]}`-1 
for (( i=3; i<${len}; i++ ));
do
    ABOVE_DIR+="/"
    ABOVE_DIR+=${CURR_DIR[i]}
done
ABOVE_DIR+="/"




#Obtain the language directories names to place into an array
IFS='
' DIR_ARRAY=(`ls -l | grep '^d'`)
for ((n=0; n<"${#DIR_ARRAY[@]}"; n++))
do
    IFS=' ' DIRECT=(${DIR_ARRAY[n]})
    if [ "${DIRECT[${#DIRECT[@]}-1]}" != "python" ]
    then
	LANG_DIRS+=(${DIRECT[${#DIRECT[@]}-1]})
    fi
done


for ((i=0; i<"${#LANG_DIRS[@]}"; i++))
do
    #THE VARIOUS LANGUAGES MUST HAVE THE WORD 'MAIN' IN THEM TO HAVE THE MAKEFILES SHOW UP IN THEIR DIRECTORIES
    IFS='
' DIR_ARRAY=(`grep '' ${LANG_DIRS[i]} -lR | grep ${LANGS_EXTENSIONS[i]}`)
    for ((n=0; n<"${#DIR_ARRAY[@]}"; n++))
    do
	#DIFFERENT LANGUAGE STRUCTURES GO HERE. 
        #Add LANGUAGENAME_DIRS as an elif statement to support the language.
        #Also build a Makefile structure at the bottom of the file to support the language.
	IFS='/' MAINS=(${DIR_ARRAY[n]})
	if [ ${LANG_DIRS[i]} == "" ]
	then
		#Do Nothing
		:
	elif [ ${LANG_DIRS[i]} == "cplusplus" ]
	then
	    CPLUSPLUS_MAINS+=( ${MAINS[${#MAINS[@]}-1]%.*})
	    CPLUSPLUS_DIRS+=( ${MAINS[${#MAINS[@]}-2]})
	elif [ ${LANG_DIRS[i]} == "java" ]
	then
	    VARTEST=( `grep 'public static void main' "${DIR_ARRAY[${n}]}" ` )
	    if [[ ${VARTEST} != "" ]]
	    then
	    	JAVA_MAINS+=(${MAINS[${#MAINS[@]}-1]%.*})
		JAVA_DIRS+=( ${MAINS[${#MAINS[@]}-2]})
	    fi
	    

	    #NEW_LANGUAGE_ADD_GOES_HERE_1
	elif [ ${LANG_DIRS[i]} == "cobol" ]
	then
	    COBOL_MAINS+=( ${MAINS[${#MAINS[@]}-1]%.*})
	    COBOL_DIRS+=( ${MAINS[${#MAINS[@]}-2]})
	elif [ ${LANG_DIRS[i]} == "fortran" ]
	then
	    FORTRAN_MAINS+=( ${MAINS[${#MAINS[@]}-1]%.*})
	    FORTRAN_DIRS+=( ${MAINS[${#MAINS[@]}-2]})
	elif [ ${LANG_DIRS[i]} == "c" ]
	then
	    C_MAINS+=( ${MAINS[${#MAINS[@]}-1]%.*})
	    C_DIRS+=( ${MAINS[${#MAINS[@]}-2]})
	fi
    done
done


echo "Generating Makefiles...."

rm -rf ~"${ABOVE_DIR}""${PROG}"/"${GEN_FILENAME}"
echo ~"${ABOVE_DIR}""${PROG}"/"${GEN_FILENAME}"
for LANGS in "${LANG_DIRS[@]}"
do
    rm -rf ~"${ABOVE_DIR}""${PROG}"/"${LANGS}"/"${GEN_FILENAME}"
    echo ~"${ABOVE_DIR}""${PROG}"/"${LANGS}"/"${GEN_FILENAME}"

    if [ ${LANGS} == "" ]
    then
	#Do Nothing
	:
    elif [ ${LANGS} == "cplusplus" ]
    then
	for PROGS in "${CPLUSPLUS_DIRS[@]}"
	do
	    rm -rf ~"${ABOVE_DIR}""${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	    echo ~"${ABOVE_DIR}""${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	done
    elif [ ${LANGS} == "java"  ]
    then
	for PROGS in "${JAVA_DIRS[@]}"
	do
	    rm -rf ~"${ABOVE_DIR}""${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	    echo ~"${ABOVE_DIR}""${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	done
	#NEW_LANGUAGE_ADD_GOES_HERE_2
    elif [ ${LANGS} == "cobol" ]
    then
	for PROGS in "${COBOL_DIRS[@]}"
	do
	    rm -rf ~"${ABOVE_DIR}${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	    echo ~"${ABOVE_DIR}${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	done
    elif [ ${LANGS} == "fortran" ]
    then
	for PROGS in "${FORTRAN_DIRS[@]}"
	do
	    rm -rf ~"${ABOVE_DIR}${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	    echo ~"${ABOVE_DIR}${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	done
    elif [ ${LANGS} == "c" ]
    then
	for PROGS in "${C_DIRS[@]}"
	do
	    rm -rf ~"${ABOVE_DIR}${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	    echo ~"${ABOVE_DIR}${PROG}"/"${LANGS}"/"${PROGS}"/"${GEN_FILENAME}"
	done
    fi
done




#MAKEFILE in compilesys/ directory
for DIR in "${PROG[@]}"
do
echo -e "SUBDIRS = ${LANG_DIRS[@]}
all: 
\t@for progs in \$""{SUBDIRS} ; do \\
\tcd \$$""{progs} ; \\
\tmake ; \\
\tcd .. ; \\
done

clean:
\t@for progs in \$""{SUBDIRS} ; do \\
\tcd \$$""{progs} ; \\
\tmake clean ; \\
\tcd .. ; \\
done

distclean:
\t@for progs in \$""{SUBDIRS} ; do \\
\tcd \$$""{progs} ; \\
\tmake distclean ; \\
\tcd .. ; \\
done
\trm -r -f "${GEN_FILENAME}"" > ${GEN_FILENAME}
done




#MAKEFILE in the different LANGUAGES Directories (c++progs javaprogs etc)
for DIR in "${LANG_DIRS[@]}"
do
    #Add new different types of language directories here!
    if [ "${DIR}" == "" ]
    then
	#Do Nothing
	:
    elif [ "${DIR}" == "cplusplus" ]
    then
	echo -e "SUBDIRS = ${CPLUSPLUS_DIRS[@]}" > ${DIR}/${GEN_FILENAME}
    elif [ "${DIR}" == "java" ]
    then
	echo -e "SUBDIRS = ${JAVA_DIRS[@]}" > ${DIR}/${GEN_FILENAME}
	#NEW_LANGUAGE_ADD_GOES_HERE_3
    elif [ "${DIR}" == "cobol" ]
    then
	echo -e "SUBDIRS = ${COBOL_DIRS[@]}" > ${DIR}/${GEN_FILENAME}
    elif [ "${DIR}" == "fortran" ]
    then
	echo -e "SUBDIRS = ${FORTRAN_DIRS[@]}" > ${DIR}/${GEN_FILENAME}
    elif [ "${DIR}" == "c" ]
    then
	echo -e "SUBDIRS = ${C_DIRS[@]}" > ${DIR}/${GEN_FILENAME}
    fi
echo -e "all: 
\t@for progs in \$""{SUBDIRS} ; do \\
\tcd \$$""{progs} ; \\
\tmake ; \\
\tcd .. ; \\
done

clean:
\t@for progs in \$""{SUBDIRS} ; do \\
\tcd \$$""{progs} ; \\
\tmake clean ; \\
\tcd .. ; \\
done

distclean:
\t@for progs in \$""{SUBDIRS} ; do \\
\tcd \$$""{progs} ; \\
\tmake distclean ; \\
\tcd .. ; \\
done
\trm -r -f "${GEN_FILENAME}"" >> ${DIR}/${GEN_FILENAME}
done



./.config_cprogs "${C_DIRS[@]}" 0 "${C_MAINS[@]}" 0 "${GEN_FILENAME[@]}" 0 
./.config_cplusplusprogs "${CPLUSPLUS_DIRS[@]}" 0 "${CPLUSPLUS_MAINS[@]}" 0 "${GEN_FILENAME[@]}" 0 
./.config_fortranprogs "${FORTRAN_DIRS[@]}" 0 "${FORTRAN_MAINS[@]}" 0 "${GEN_FILENAME[@]}" 0 
./.config_javaprogs "${JAVA_DIRS[@]}" 0 "${JAVA_MAINS[@]}" 0 "${GEN_FILENAME[@]}" 0 
./.config_cobolprogs "${COBOL_DIRS[@]}" 0  "${COBOL_MAINS[@]}" 0 "${GEN_FILENAME[@]}" 0 
